


spring:
  # 配置数据源
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/the_batis?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF8&useSSL=false&serverTimezone=Asia/Shanghai


    # MySQL在高版本需要指明是否进行SSL连接 解决则加上 &useSSL=false
    username: root
#    password: 8317992